import { Preset, DEFAULT_SETTINGS } from "../types";

export const SYSTEM_PRESETS: Preset[] = [
  {
    id: "p1",
    name: "Amanecer Cálido",
    category: "Naturaleza",
    isSystem: true,
    planRequired: "free",
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 110,
      contrast: 105,
      saturation: 120,
      exposure: 5,
      warmth: 15,
    }
  },
  {
    id: "p2",
    name: "Boda Elegante",
    category: "Eventos",
    isSystem: true,
    planRequired: "pro",
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 115,
      contrast: 95,
      saturation: 90,
      exposure: 10,
      warmth: 5,
      tint: 5,
      highlights: 110,
      shadows: 105,
      whites: 105,
      blacks: 95,
      clarity: 10,
      vibrance: 110,
      sharpening: 20,
      vignette: 10,
    }
  },
  {
    id: "p3",
    name: "Urbano Brutalista",
    category: "Arquitectura",
    isSystem: true,
    planRequired: "pro",
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 90,
      contrast: 130,
      saturation: 80,
      exposure: -5,
      warmth: -10,
      tint: -5,
      highlights: 90,
      shadows: 85,
      whites: 95,
      blacks: 80,
      clarity: 40,
      vibrance: 90,
      sharpening: 50,
      vignette: 20,
    }
  },
  {
    id: "p4",
    name: "Cine Noir",
    category: "Retrato",
    isSystem: true,
    planRequired: "studio",
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 85,
      contrast: 150,
      saturation: 0,
      exposure: -10,
      warmth: 0,
      tint: 0,
      highlights: 80,
      shadows: 70,
      whites: 90,
      blacks: 60,
      clarity: 60,
      vibrance: 0,
      sharpening: 40,
      vignette: 40,
    }
  },
  {
    id: "p5",
    name: "Golden Hour Pro",
    category: "Naturaleza",
    isSystem: true,
    planRequired: "studio",
    settings: {
      ...DEFAULT_SETTINGS,
      brightness: 120,
      contrast: 110,
      saturation: 140,
      exposure: 15,
      warmth: 30,
      tint: 10,
      highlights: 120,
      shadows: 110,
      whites: 115,
      blacks: 105,
      clarity: 20,
      vibrance: 130,
      sharpening: 30,
      vignette: 15,
    }
  }
];
